Try macos-13 which is what maturin generates.
macos-14 + x86_64 failing with:
ERROR: Could not find a version that satisfies the requirement cedarpy (from versions: none)
ERROR: No matching distribution found for cedarpy